### ISSUE TITLE
Colab requests, EmoTalk_release and synctalk

### ISSUE THREAD

**Issue by G-force78** [camenduru/camenduru#2]
https://github.com/psyai-net/EmoTalk_release   (done, https://colab.research.google.com/drive/1oZ0SxK9FAB4zb6BUYK0YPNvJNnzq7Ffo#scrollTo=z9zaSq4B246R) (ok already a working one for synctalk https://colab.research.google.com/drive/1upy851uib9BHI7ZasJcH7R2Pjs4oKuw2#scrollTo=QpU-tRFQNtVK )

https://github.com/ZiqiaoPeng/SyncTalk

also for your information there is another new one thats awaiting code release

https://github.com/tanshuai0219/EDTalk

**Comment by camenduru** [comment]
without the  `Preprocessing Code` we can't use with custom videos 😐

![image](https://github.com/camenduru/camenduru/assets/54370274/5bf9289b-760b-4f56-87d8-28e56ef7939f)
from https://github.com/ZiqiaoPeng/SyncTalk

https://github.com/camenduru/SyncTalk-jupyter

**Comment by camenduru** [comment]
https://github.com/ZiqiaoPeng/SyncTalk/issues/11#issuecomment-1976493169
![image](https://github.com/camenduru/camenduru/assets/54370274/cc54d1ed-735e-4bc5-bc06-a65c1899562c)

**Comment by G-force78** [comment]
> [ZiqiaoPeng/SyncTalk#11 (comment)](https://github.com/ZiqiaoPeng/SyncTalk/issues/11#issuecomment-1976493169) ![image](https://private-user-images.githubusercontent.com/54370274/320693885-cc54d1ed-735e-4bc5-bc06-a65c1899562c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ5ODEwMjcsIm5iZiI6MTcxNDk4MDcyNywicGF0aCI6Ii81NDM3MDI3NC8zMjA2OTM4ODUtY2M1NGQxZWQtNzM1ZS00YmM1LWJjMDYtYTY1YzE4OTk1NjJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA2VDA3MzIwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg3ODk4YzI1NTY5Y2MxZTJiMDRkM2ZhMmRiYjczYmU2ZDE4MGE2MjllZWM1NzczMTA2OWI3OTYwYjNiZmE0ZDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Vkcbvy_eyfp46UPkLSXPoRJ3B6LE-CepojthhuzgsCs)

Has been released

**Comment by G-force78** [comment]
https://github.com/TMElyralab/MusePose new improved on moore-animate

**Comment by camenduru** [comment]
@G-force78  https://github.com/camenduru/MusePose-jupyter
